version: 2
jobs:
  build_and_deploy:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - run:
          command: |
            sudo npm install -g now
            sudo pip install datasette yaml-to-sqlite requests
            yaml-to-sqlite museums.db museums museums.yaml --pk=id
            python nominatum_annotate.py museums.db
            datasette publish now museums.db --token=$NOW_TOKEN \
              --alias=www.niche-museums.com \
              --name=niche-museums \
              --install=datasette-haversine \
              --install=datasette-pretty-json \
              --install=datasette-json-html \
              --install=datasette-cluster-map~=0.8 \
              --metadata=metadata.json \
              --template-dir=templates \
              --branch=master

workflows:
  version: 2
  build:
    jobs:
      - build_and_deploy
